"""Blind L2 quality judge for A/B response pairs."""
from __future__ import annotations

import json
import logging
import os
import random
import re
from dataclasses import dataclass

from src.brain.llm_caller import call_raw

logger = logging.getLogger(__name__)


# Judge model defaults to GPT-5.4-thinking (analysis tier in the user's
# multi-provider setup; reachable via STS2_GPT_BASE_URL/_API_KEY).
# Override with STS2_PROMPT_AB_JUDGE_MODEL.
_DEFAULT_JUDGE_MODEL = "gpt-5.4-thinking"


_JUDGE_SYSTEM = """You are a blind A/B reviewer of two responses to the same Slay the Spire 2 card-reward decision. Your job is to score each on a 4-dimension rubric and pick a winner.

You do NOT know which response was generated by which prompt variant. Be impartial and rubric-driven.

Output format (strict JSON inside <verdict>...</verdict>):
{
  "scores": {
    "option_1": {"soundness": 1-5, "coverage": 1-5, "coherence": 1-5, "risk_awareness": 1-5},
    "option_2": {"soundness": 1-5, "coverage": 1-5, "coherence": 1-5, "risk_awareness": 1-5}
  },
  "winner": "option_1" | "option_2" | "tie",
  "rationale": "<2-3 sentence explanation>"
}

Rubric:
- soundness: does the chosen card improve the deck given current state and boss matchup?
- coverage: does the response cite relevant deck dimensions (Damage/Defense/Draw/Energy), boss DPS target, and rarity?
- coherence: does it align with the Strategic Thread / build trajectory shown in the user message?
- risk_awareness: does it acknowledge what's being given up (skipped cards, deck bloat, archetype dilution)?
"""


@dataclass(frozen=True)
class JudgeVerdict:
    """One blind judge verdict for an A/B pair."""
    winner: str  # "A", "B", or "tie"
    score_a: dict[str, int]
    score_b: dict[str, int]
    rationale: str
    malformed: bool = False
    raw_response: str = ""


_VERDICT_RE = re.compile(r"<verdict>\s*(\{.*?\})\s*</verdict>", re.DOTALL)


def _build_judge_user_message(
    *,
    user_message_summary: str,
    response_a: str,
    response_b: str,
    swap: bool,
) -> tuple[str, str, str]:
    """Build user message with randomized A/B labeling.

    Returns (user_message, label_for_a, label_for_b) where labels are either
    'option_1' or 'option_2'.
    """
    if swap:
        first_resp, second_resp = response_b, response_a
        label_a, label_b = "option_2", "option_1"
    else:
        first_resp, second_resp = response_a, response_b
        label_a, label_b = "option_1", "option_2"
    user = (
        "## Decision context (excerpt of user message shown to both options)\n\n"
        + user_message_summary
        + "\n\n## option_1 response\n\n"
        + first_resp
        + "\n\n## option_2 response\n\n"
        + second_resp
        + "\n\nScore both options strictly per the rubric and emit the JSON verdict."
    )
    return user, label_a, label_b


def _truncate_user_message_for_judge(user_message: str, max_chars: int = 6000) -> str:
    """Trim user message to keep judge prompt small but informative.

    Keeps the first 4000 chars (covers headers + early context) and the last
    2000 chars (covers options + eval framework).
    """
    if len(user_message) <= max_chars:
        return user_message
    head = user_message[:4000]
    tail = user_message[-2000:]
    return head + "\n\n[... TRUNCATED ...]\n\n" + tail


async def judge_pair(
    *,
    user_message: str,
    response_a: str,
    response_b: str,
    seed: int = 0,
) -> JudgeVerdict:
    """Run one blind judge call. Position swap is RNG-controlled by ``seed``."""
    if not response_a or not response_b:
        return JudgeVerdict(
            winner="tie", score_a={}, score_b={},
            rationale="empty response", malformed=True,
        )

    rng = random.Random(seed)
    swap = rng.random() < 0.5

    user_summary = _truncate_user_message_for_judge(user_message)
    user_msg, _label_a, _label_b = _build_judge_user_message(
        user_message_summary=user_summary,
        response_a=response_a,
        response_b=response_b,
        swap=swap,
    )

    judge_model = os.environ.get("STS2_PROMPT_AB_JUDGE_MODEL", _DEFAULT_JUDGE_MODEL)
    text, _latency, _tokens = await call_raw(
        system=_JUDGE_SYSTEM,
        prompt=user_msg,
        model=judge_model,
        call_type="prompt_ab_judge",
        call_class="postrun_summary",
    )

    m = _VERDICT_RE.search(text)
    if m is None:
        return JudgeVerdict(
            winner="tie", score_a={}, score_b={},
            rationale="no verdict block", malformed=True, raw_response=text,
        )
    try:
        obj = json.loads(m.group(1))
    except json.JSONDecodeError:
        return JudgeVerdict(
            winner="tie", score_a={}, score_b={},
            rationale="invalid json", malformed=True, raw_response=text,
        )

    raw_winner = str(obj.get("winner") or "tie")
    scores = obj.get("scores") or {}
    score_first = dict(scores.get("option_1") or {})
    score_second = dict(scores.get("option_2") or {})

    if swap:
        score_a = score_second
        score_b = score_first
        if raw_winner == "option_1":
            winner = "B"
        elif raw_winner == "option_2":
            winner = "A"
        else:
            winner = "tie"
    else:
        score_a = score_first
        score_b = score_second
        if raw_winner == "option_1":
            winner = "A"
        elif raw_winner == "option_2":
            winner = "B"
        else:
            winner = "tie"

    return JudgeVerdict(
        winner=winner,
        score_a=score_a,
        score_b=score_b,
        rationale=str(obj.get("rationale") or ""),
        malformed=False,
        raw_response=text,
    )
