"""Keyword glossary shared across combat and non-combat prompts.

Scans card rules_text for known keywords and returns concise definitions.

Priority chain for mechanic lookups:
  1. KW_GLOSSARY — hand-written, authoritative definitions (preferred)
  2. _dll_mechanics — auto-extracted from game DLL at agent startup (fallback for
     mechanics not yet in KW_GLOSSARY; never falls back to local markdown/json KB)
"""

from __future__ import annotations

import json
import logging
import re
from pathlib import Path

logger = logging.getLogger(__name__)

# Keyword → one-line description.
# Keep keys lowercase for matching. Keep descriptions concise (deck-building context).
KW_GLOSSARY: dict[str, str] = {
    "block": "Block: Absorbs damage until your next turn, then resets to 0.",
    "weak": "Weak: Target deals 25% less Attack damage for N turns.",
    "vulnerable": "Vulnerable: Target takes 50% more Attack damage for N turns.",
    "poison": (
        "Poison: Loses N HP at the start of its turn, before it acts "
        "(attack or buff), then decreases by 1. Bypasses Block."
    ),
    "strength": "Strength: Adds N damage to each Attack hit. Multi-hit cards benefit enormously.",
    "dexterity": "Dexterity: Adds N Block to each Block card.",
    "frail": "Frail: Block from cards reduced by 25%.",
    "artifact": "Artifact: Negates N debuffs. Check enemy Artifact before applying debuffs — they'll be wasted.",
    "sly": "Sly: If discarded BY A CARD EFFECT (e.g. Survivor, Acrobatics), this card is PLAYED FOR FREE. End-of-turn auto-discard does NOT trigger Sly.",
    "ethereal": "Ethereal: Exhausted if still in hand at end of turn. If Unplayable, keep it — auto-exhaust removes it this combat. Don't discard it.",
    "retain": "Retain: Stays in hand at end of turn instead of being discarded.",
    "exhaust": "Exhaust: Removed from combat permanently after use. Thins deck, but you can never play this card again — bad for damage cards you want every cycle.",
    "innate": "Innate: Always in your opening hand.",
    "eternal": "Eternal: Cannot be removed or transformed from your deck.",
    "unplayable": "Unplayable: Cannot be played from hand. Only for discard/exhaust synergies.",
    "shiv": "Shiv: 0-cost Attack that deals 4 damage and Exhausts. Generated by Blade Dance, Cloak and Dagger, etc.",
    "intangible": "Intangible: Reduce all damage taken and HP loss to 1 this turn.",
    "scry": "Scry: Look at N cards from the top of your draw pile. Discard any you don't want.",
    "channel": "Channel: Place an Orb into the next empty slot. If full, evoke the leftmost Orb first.",
    "replay": (
        "Replay N: When played, this card plays N additional times "
        "(N+1 total plays per turn). All damage, block, and power effects trigger "
        "for each play. Game-changing effect."
    ),
}

# ── DLL-extracted fallback ─────────────────────────────────────────────────────

def _load_dll_mechanics() -> dict[str, str]:
    """Load DLL-extracted mechanic descriptions as fallback for unknown terms.

    Called once at module load. Returns empty dict silently if the file is absent.
    File is written by scripts/extract_mechanics_from_dll.py at agent startup.
    """
    candidate = Path(__file__).resolve().parents[3] / "data/knowledge/upstream/mechanics_dll.json"
    if not candidate.exists():
        return {}
    try:
        with candidate.open(encoding="utf-8") as f:
            data = json.load(f)
        if isinstance(data, dict):
            logger.debug("Loaded %d DLL mechanic definitions", len(data))
            return {k.lower(): v for k, v in data.items()}
    except Exception as exc:
        logger.debug("Could not load mechanics_dll.json: %s", exc)
    return {}


# Loaded once at import — lightweight JSON read.
_dll_mechanics: dict[str, str] = _load_dll_mechanics()


def format_keyword_glossary(card_texts: list[str]) -> str:
    """Scan card texts for known keywords and return a glossary section.

    Checks KW_GLOSSARY first (hand-written), then _dll_mechanics (DLL-extracted)
    for any mechanics not already covered. Local markdown/JSON knowledge base
    is intentionally NOT consulted here.

    Args:
        card_texts: List of card rules_text strings to scan for keywords.

    Returns:
        A "## Keyword Glossary" section string, or empty string if no keywords matched.
    """
    # Tier 1 (hand-written) uses case-insensitive substring match — KW_GLOSSARY
    # keys are short and tolerate both capitalized ("Gain 5 Block") and generic
    # ("blocked") references. Apostrophes stripped so keys like "ascenders bane"
    # compare cleanly to text containing "Ascender's Bane".
    search_text_lower = " ".join(t.lower() for t in card_texts if t)
    search_text_lower = search_text_lower.replace("'", "").replace("\u2019", "")

    # Tier 2 (DLL-extracted) matches case-sensitively against ORIGINAL case.
    # DLL keys are class names (Focus, Doubt, Burn, PerfectFit) that the game
    # always capitalizes as proper nouns. Lowercase-only matching produced
    # false positives on ordinary English ("reasonable doubt" in event text,
    # "burn damage" as flavor). Requiring title-case on the match side kills
    # those without missing real mechanic references.
    search_text_orig = " ".join(t for t in card_texts if t)
    search_text_orig = search_text_orig.replace("'", "").replace("\u2019", "")

    lines: list[str] = []
    # Tier 1: hand-written glossary (authoritative)
    for kw, desc in KW_GLOSSARY.items():
        if kw in search_text_lower:
            lines.append(f"- {desc}")

    # Tier 2: DLL-extracted fallback (only for mechanics not already in KW_GLOSSARY).
    # Word-boundary match so short affliction names (e.g. "bound") don't false-match
    # inside unrelated words like "rebound".
    for kw, desc in _dll_mechanics.items():
        if kw in KW_GLOSSARY:
            continue
        # Skip placeholder definitions from the DLL extractor's generic fallback
        # (extract_mechanics_from_dll.py emits "<name>: ... See game UI for
        # details." when it can't decode the card body). Injecting that into a
        # prompt is worse than omitting the entry.
        desc_l = desc.lower()
        if "see game ui for details" in desc_l or "a power used by" in desc_l:
            continue
        # Build title-case pattern from the space-separated lowercase key:
        # "perfect fit" → "Perfect Fit"; "stun" → "Stun". The game may also
        # render keywords with colons like "Weak:" inside card text; word-
        # boundary `\b` already accommodates that.
        title = " ".join(w.capitalize() for w in kw.split())
        if re.search(rf"\b{re.escape(title)}\b", search_text_orig):
            lines.append(f"- {desc}")

    if not lines:
        return ""
    return "\n".join(["", "## Keyword Glossary"] + lines)
